### PR TITLE
Fixing Resources - ResourcesImageLibrary

### PR DESCRIPTION
**Pull request by Tohaker**
From what I can tell, the rest of the games that rely on a resources folder all use the `LazyImageLibrary` to gather their Images. To save time and maintain portability, I've extended the `AbstractImageLibrary` to act in exactly the same way, but by using the `ResourceFileManager` instead to find the files. Over the next week I'll work on retrofitting the games that use the `LazyImageLibrary` with this new library instead.

### CODE REVIEW

**Comment by Tohaker** [comment]
The following games are fixed with this PR:
* Blocks
* Bubble
* Portrait 
* Divisor
* Letters
* MagicCards
* Memory

I have duplicated the contents of the `data/common` resource directory to `gazeplay-games` to ensure that this PR works standalone. Once all the games are fixed, I will make one last PR to reduce the duplication as much as possible and keep the project at a reasonable size.

_Extra:_ This PR also included the fix for the `distZip` package having duplicated scripts.

**Comment by YannRobert** [comment]
very good

**Comment by schwabdidier** [comment]
So we can merge it @YannRobert  ?

**Comment by YannRobert** [comment]
I don't know if Miles recommends to merge ASAP, or to wait for the other PR to be ready.
Anyways is fine to me.

**Comment by Tohaker** [comment]
I've left the other PR in draft so it didn't get merged before this one.
This is ready to merge now, and once it is I'll mark the other one as ready :)

**Pull request merged**
