### PR TITLE
Setup for Integration Tests and Testing Documentation

### PR DESCRIPTION
**Pull request by Tohaker**
I tried to make an example integration test but it appears like significant work is needed to make this happen... Anyway I thought I'd leave in the setup as it will be useful when someone eventually adds some in. 
I've also added in a document on how to write tests as per request.

### CODE REVIEW

**Comment by schwabdidier** [comment]
Please check Travis @Tohaker

**Comment by Tohaker** [comment]
Travis is fine, GitHub actions is failing as usual...

**Comment by schwabdidier** [comment]
oh, you are right :) sorry

**Comment by YannRobert** [comment]
@Tohaker Please don't do PR from upstream repository to your personal repository

This creates additional merge commit that is showing when you're doing a PR back to the upstream repository.

I suggest you update your personal repository this way :
```
git co master
git pull upstream master
git push myrepo master
git co -b MyChange
# do your change
git push myrepo MyChange
git co master
```

**Comment by YannRobert** [comment]
I think the project source tree should not contain general knowledge documentation (like programming or testing), because this may be an infinite work to do, and there are plenty of other resources that provide this already.

What could be done is to include in the CONTRIBUTING.MD the instructions on the guidelines to respect in order to contribute to this repository, where you would want to state that we like tests and well-crafted piece of code (but not explain how to do it).

**Comment by Tohaker** [comment]
Thanks for telling me about the upstream pulls, GitHub just tells you to do a PR between repos but your way makes way more sense :)

**Comment by Tohaker** [comment]
Git doesn't allow me to squash into the first commit, as that is from Master... I'll do a squash when I merge in this time, and follow your upstream pull instructions next time

**Comment by Tohaker** [comment]
Well that didn't work like I wanted it to 😆 I'm just gonna squash this when I merge, theres no need to preserve the commits here.

**Comment by YannRobert** [comment]
I don't like squash and merge because it does not produce a merge commit.
Also as anybody can hit the "merge pull request" you are not safe that this exact history won't be merged.
Best way is to have the PR the exact way you want it to be merged.

To achieve this you should rebase
```
git co master
git pull upstream master
git co MyChange
git rebase -i master
Use 's' on the first two lines/commit
Save
Edit the squash commit message
Save
Force push to your repo
```

**Comment by Tohaker** [comment]
Yes I did a rebase,  but it still kept those merges I did before into master. How can I fix those first two?

**Comment by YannRobert** [comment]
In fact you need to mark as squashed the line 2 and 3 
When executing rebase -i

**Comment by Tohaker** [comment]
Welp I've managed to completely destroy my local branch, can't rebase anymore. I'll start a new PR

**Pull request closed without merging**
