### PR TITLE
MacOS and Windows: Fix command line scripts

### PR DESCRIPTION
**Pull request by Tohaker**
Finishing off the work required to solve #918 
Please test this locally to get the best understanding if this solves the problem.

### CODE REVIEW

**Comment by Tohaker** [comment]
MacOS works locally.
I will test Windows 10 when I am back at my home PC.

**Comment by Tohaker** [comment]
Windows isn't working still for me. It boots but doesn't load any games in.
@schwabdidier would you be able to see if you can replicate it on your Windows computers?

**Comment by YannRobert** [comment]
Please set the JAVA_HOME first
to use the provided JRE

```
@echo on


SET JAVA_HOME=..\lib\jre
SET PATH=%JAVA_HOME%\bin;%PATH%;%LocalAppData%\TobiiStreamEngineForJava\lib\tobii\x64

java -cp "..\lib\*" -Xms256m -Xmx1g net.gazeplay.GazePlayLauncher

pause
```

I think this is cleaner.

**Comment by YannRobert** [comment]
@schwabdidier Why is there 2 distinct files ```gazeplay.bat``` and ```gazeplay-win10.bat``` ?

I think what maybe useful is to have 
```gazeplay.bat``` : use java from PATH, if the system already have a proper java installed
```gazeplay-provided-jre.bat``` : use java from lib/jre, that is provided in the gazeplay distribution

**Comment by YannRobert** [comment]
> I think what maybe useful is to have
> `gazeplay.bat` : use java from PATH, if the system already have a proper java installed
> `gazeplay-provided-jre.bat` : use java from lib/jre, that is provided in the gazeplay distribution

On second thought, I guess most of users would double click the ```gazeplay.bat``` by default, not knowing "what a JRE is".
I guess we want most of users to use the provided JRE, as this gives an additional guarantee that the program will run as expected.

Maybe advanced users will know what a JRE is and dare to click on a .bat mentioning it.

So I would maybe use
```gazeplay.bat``` for launching with the provided JRE
```gazeplay-java.bat``` (or whatever) for launching with the existing (if any) JRE

and maybe there should be a friendly message if java is not found in PATH

**Comment by schwabdidier** [comment]
For next release, gazeplay-win10 is not very useful. In fact, with last version, I add a JVM from java10 and then I knew it works on win 10 while I was not sure on other versions. It seems it works on java 7 so gazeplay-win10 uses the embedded JVM (on any windows) and gazeplay.bat use the local JVM. 

For next release , I guess gazeplay.bat could be the only launcher for windows. Why someone would like to use his local Java ?

**Comment by Tohaker** [comment]
I agree that we should only have one launcher for each OS. If someone want's to run it with some custom version of Java they should know how to do it themselves. These launch scripts are for people who just want things to _work_

**Pull request merged**
