### PR TITLE
Realtime Volume Slider

### PR DESCRIPTION
**Pull request by Tohaker**
As reported in Issue #956 the volume slider doesn't actually change the volume whilst the application is open. 
The main fix in this PR is the addition of a Bidirectional Bind between the GazePlay volume property and the volume slider, as well as the implementation of the actual volume change to the MediaPlayer, which (for some reason) wasn't ever used.

_Note: This does not affect the `effect` volume. I will try to see if that volume works and fix if necessary in another PR_

### CODE REVIEW

**Comment by schwabdidier** [comment]
There are problems with tests

**Comment by Tohaker** [comment]
I thought there might be - it may be trying to play sounds. I'll debug it.

**Comment by Tohaker** [comment]
The TestFX library seems to have been barren for a long time now, I've raised an issue about this but it seems like they may not respond. I'll block these tests from running in the pipeline and see if it passes.

**Comment by Tohaker** [comment]
Ok the CI passes now without my new tests 👎  but they definitely work 👍 locally. GitHub won't let me resolve the conflict so I'll need someone else to do that.

**Comment by YannRobert** [comment]
You have to resolve conflicts @Tohaker 
You don't need github to do this; 
you can do it in your local repository and then push again.

**Comment by Tohaker** [comment]
Should all be good now!

**Comment by Tohaker** [comment]
@YannRobert could you take another look please?

**Pull request merged**
