### PR TITLE
add github action for gradle build

### PR DESCRIPTION
**Pull request by YannRobert**

### CODE REVIEW

**Comment by Tohaker** [comment]
Why are we ignoring tests? We want to know if something has broken surely?

**Comment by Tohaker** [comment]
You need to `export DISPLAY=:99.0` somewhere in the YAML for the JavaFX tests to work.

**Comment by YannRobert** [comment]
xvfb is pre-installed on Travis
with github actions it needs to be installed first.

**Comment by Tohaker** [comment]
Is the intention to use Actions instead of Travis now?

**Comment by YannRobert** [comment]
The intention is to evaluate it.
Let's use it in parallel for a while.

Actions seems to provide many more possibilities.

**Pull request merged**
