### PR TITLE
Update web site with s3 download link

### PR DESCRIPTION
**Pull request by kuhlkrein**
Update web site with AWS Amazon s3 bucket link for advance users and developper on eng and fr installation pages

### CODE REVIEW

**Comment by schwabdidier** [comment]
I checked[]( https://kuhlkrein.github.io/GazePlay/installation/ ) and there is a problem with the link  [](https://gazeplay-dist.s3.eu-west-3.amazonaws.com/), how can we get the installers ? I checked the link and it it the one provided by @YannRobert . How to manage that ? It is certainly connected with that [](https://forums.aws.amazon.com/message.jspa?messageID=753323)

**Comment by schwabdidier** [comment]
I checked[]( https://kuhlkrein.github.io/GazePlay/installation/ ) and there is a problem with the link  [](https://gazeplay-dist.s3.eu-west-3.amazonaws.com/), how can we get the installers ? I checked the link and it it the one provided by @YannRobert . How to manage that ? It is certainly connected with that [](https://forums.aws.amazon.com/message.jspa?messageID=753323)

**Comment by Tohaker** [comment]
The link you've given just loads a plaintext listing of the bucket, you'll need to provide explicit links to the bucket browser here: https://s3.console.aws.amazon.com/s3/buckets/gazeplay-dist/?region=eu-west-3
I would also recommend updating the installation page that Didier linked, it's not up to date.

**Comment by YannRobert** [comment]
In the S3 bucket, there is an ```index.html``` file than renders the content listing as a directory listing.
I just improved it a bit.

So the link would be : 
https://gazeplay-dist.s3.eu-west-3.amazonaws.com/index.html

You can also include the following snippet into the ```installation.md``` github page.
To have embedded content in the github page.

```markdown
## Snapshot versions

You can download latest development version

<div class="iframe_container">
<iframe src="https://gazeplay-dist.s3.eu-west-3.amazonaws.com/index.html" style="border:0; width: 60em; height: 20em"></iframe>
</div>
```

**Comment by kuhlkrein** [comment]
Thanks a lot @YannRobert, it's really better with the index :)

**Comment by kuhlkrein** [comment]
Well, I tried with the snippet but I think it's maybe better to just keep the basic link no ?

**Pull request merged**
