### PR TITLE
Coloring game printing #1327

### PR DESCRIPTION
**Pull request by Iluvrog**
The picture can be flatten if the picture is with the wrong format
The button's name is not translate

### CODE REVIEW

**Comment by Iluvrog** [comment]
it's done

**Review by PillouMatou — APPROVED** [review]
It's fine for me @kuhlkrein

**Review by kuhlkrein — APPROVED** [review]
Looks good to me

**Review by kuhlkrein — CHANGES_REQUESTED** [review]
The code is good but when in full screen I have a small issue because the print window is being displayed behind the gazeplay window.. do you think you can change that ?

**Comment by Iluvrog** [comment]
> The code is good but when in full screen I have a small issue because the print window is being displayed behind the gazeplay window.. do you think you can change that ?

I'm not sure if I can change that ; in my computer, it's fine

**Comment by kuhlkrein** [comment]
Ok I see, the problem seems to be on  linux so I think we will add this as an issue after having merge this PR :)

**Comment by kuhlkrein** [comment]
image

I have a problem with the side pane, it is really yellow now can you bring the normal color back ?

**Comment by Iluvrog** [comment]
> image
> 
> I have a problem with the side pane, it is really yellow now can you bring the normal color back ?

It's fix

**Review by kuhlkrein — APPROVED** [review]
Looks good to me, still some issues on linux that needs to be fixed later

**Pull request merged**
