### PR TITLE
Releasing 1.8.0

### PR DESCRIPTION
**Pull request by kuhlkrein**

### CODE REVIEW

**Review by schwabdidier — APPROVED** [review]

**Comment by kuhlkrein** [comment]
Hello @Tohaker do you know how to restart the travis build ? looks like there was a network issue:

> Could not resolve all files for configuration ':gazeplay-commons:testRuntimeClasspath'.
   > Could not download javafx-web-11.0.2-linux.jar (org.openjfx:javafx-web:11.0.2)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/openjfx/javafx-web/11.0.2/javafx-web-11.0.2-linux.jar'.
         > Connection reset

**Comment by Tohaker** [comment]
You can push an empty commit, but with @schwabdidier 's permission I'd like to completely remove Travis from our checks (i.e. delete the webhook in the repo), because it gives us no value.

**Comment by kuhlkrein** [comment]
thank you @Tohaker could you aprouve the PR so that we can merge when travis is done ?

**Review by schwabdidier — DISMISSED** [review]

**Review by Tohaker — APPROVED** [review]

**Review by schwabdidier — APPROVED** [review]

**Comment by kuhlkrein** [comment]
sorry @Tohaker we remove travis so we need another aprove

**Review by Tohaker — APPROVED** [review]

**Pull request merged**
