### PR TITLE
Soundsoflive new variant sea

### PR DESCRIPTION
**Pull request by Iluvrog**
For the song, I have done what I may (not sure if it says in english)

### CODE REVIEW

**Comment by Noars** [comment]
The basic music should be deactivated (songidea (copycat) _0) because it exceeds in volume the noise of the animals that we want to hear otherwise all the rest works without problem.

**Review by PillouMatou — CHANGES_REQUESTED** [review]
It works well, it might be necessary to remove or reduce the sound of the launcher because it covers the sound of the animals

**Review by kuhlkrein — CHANGES_REQUESTED** [review]
Please remove the background music

**Comment by Iluvrog** [comment]
@Noars @PillouMatou @kuhlkrein , the background music is stopping

**Review by kuhlkrein — APPROVED** [review]
looks good to me !

**Pull request merged**
