### PR TITLE
Changing the Backgound Music for games

### LINKED ISSUE #1011: Background Music doesn't change on game launch
For exemple in biboules and robot game, the music should be different than the main music:

```
public class BibouleGameSpecSource implements GameSpecSource {
    @Override
    public GameSpec getGameSpec() {
        return new GameSpec(
            GameSummary.builder().nameCode("Biboule").gameThumbnail("data/Thumbnails/biboules.png").category(GameCategories.Category.SELECTION)
                .backgroundMusicUrl("https://opengameart.org/sites/default/files/TalkingCuteChiptune_0.mp3").build(),
            new ShooterGameLauncher());
    }
}
```

### PR DESCRIPTION
**Pull request by Tohaker**
This intends to fix #1011 

The initial idea is to check if the default music is playing, and use that as a basis for whether the user wants to hear their own music, or the music chosen by us for the game. I believe we should always favour the user's music.

Next steps are to make sure the default music is restarted when the game exits.

### CODE REVIEW

**Comment by Tohaker** [comment]
A backup system for the music manager has been implemented. It's set to backup if it sees the default music playing (which implies that the user hasn't added any custom music) and restores when the game exits to home. 
Please correct me if this isn't the right logic.

**Comment by YannRobert** [comment]
Do you want to squash your last commit ?

**Comment by Tohaker** [comment]
Can we instead squash this when merging? It's a dropdown option on GitHub. The last squash I did reverted to the last check too as no code had changed.

**Comment by YannRobert** [comment]
Sure we can squash all commits. 
It's generally better to have PRs prepared the way we like it to be.
The history of this PR may be worth keeping, except last commit.

That's why I'm asking.

**Comment by Tohaker** [comment]
Ideally you'd be right, but for some reason GitHub Actions isn't as stable when it comes to installing all dependencies - sometimes it does and sometimes it doesn't... Would be very handy if we could retry a build without having to commit again

**Comment by YannRobert** [comment]
You need ```Write``` permission to re-run an Action.
I just granted you this permission.

**Comment by Tohaker** [comment]
I'll squash and rebuild shortly, thank you!

**Comment by schwabdidier** [comment]
@Tohaker @YannRobert Where are we with this PR ?

**Comment by Tohaker** [comment]
It's ready to be reviewed

**Comment by YannRobert** [comment]
Code change is ok.
Need to check if behavior change is OK.

**Pull request merged**
