### PR TITLE
Add the option to modifty progress bar size & color

### PR DESCRIPTION
**Pull request by SaviorSeva**
Issues 1554 solved for Math101 Game from my branch "Something"

### CODE REVIEW

**Comment by Noars** [comment]
For the issue #1555 as well

**Review by PillouMatou — CHANGES_REQUESTED** [review]
put the minimum for the slider to 0% to 25% because at 0% we shouldn't see the progress indicator and we can disable it in another setting.

**Review by Noars — COMMENTED** [review]
It work fine !
But yes, the minimum limit for progressIndicator size should not be 0

**Comment by SaviorSeva** [comment]
> 

I see the problem I'll find an appropriate lowest size value and tune it a bit later

**Review by PillouMatou — APPROVED** [review]
it's fine for me 👍

**Pull request merged**
