### PR TITLE
New game whack a mole with user's portraits #531

### PR DESCRIPTION
**Pull request by Iluvrog**

### CODE REVIEW

**Comment by Noars** [comment]
After several tests, it works without problem !

**Review by PillouMatou — APPROVED** [review]
Everything work well for me, @schwabdidier  @kuhlkrein

**Comment by kuhlkrein** [comment]
Hello! I'm not so sure it was the point of the issue, for me it was more about being able to import custom images like the user and user's family portraits, did I misunderstood it @schwabdidier ?

**Comment by Iluvrog** [comment]
> Hello! I'm not so sure it was the point of the issue, for me it was more about being able to import custom images like the user and user's family portraits, did I misunderstood it @schwabdidier ?

now it's with the files in the portrait depository and no the user's portait

**Review by kuhlkrein — APPROVED** [review]

**Pull request merged**
