### PR TITLE
Fixed pr for Dynamic Memory and Ninja games

### PR DESCRIPTION
**Pull request by verafili**
The previous version should be deleted

### CODE REVIEW

**Review by kuhlkrein — APPROVED** [review]
looks good to me

**Review by kuhlkrein — CHANGES_REQUESTED** [review]
Please try to rebase here to to not display the "fixation length" commits in this PR

**Comment by PillouMatou** [comment]
the "fixation length" is still in the game
image

**Comment by Noars** [comment]
I try and it work fine !

**Review by kuhlkrein — APPROVED** [review]

**Pull request merged**
