### PR TITLE
TobiiStreamEngineForJava:3.0 -> TobiiStreamEngineForJava:4.0

### PR DESCRIPTION
**Pull request by kuhlkrein**
Working with linux when drivers are installed.

### CODE REVIEW

**Comment by Tohaker** [comment]
I'd recommend a note in the documentation that links to the TobiiStreamEngineForJava repo so users can find out how to install the drivers.

**Comment by YannRobert** [comment]
Does it work out of the box ?
Please give some time for all people to evaluate this branch before merging

**Comment by schwabdidier** [comment]
What does "out of the box" mean here @YannRobert ?

**Comment by YannRobert** [comment]
Sorry I mean 

Does it need external dependencies already installed ?
If so, what are they ?

Or are all dependencies provided with gazeplay ?

**Comment by schwabdidier** [comment]
In fact, it is exactly like this for windows. With Loïc, we think that we need a particular repository for that as other people certainly would like to use 4C with Java. Anyway, I will discuss with him about the opportunity to put it under the GazePlay umbrella instead of coylz

**Comment by Tohaker** [comment]
I think we should include a Gradle task to download the drivers if the user is on Linux, then we have something of an "out the box" solution

**Comment by Tohaker** [comment]
If you wanted to, you could use this: https://github.com/michel-kraemer/gradle-download-task#download-and-extract-a-zip-file
Then make an `exec` command to run the `install_all.sh`

**Comment by Tohaker** [comment]
I've tried your branch, works perfectly well for me on Windows. I'm happy for this to go in, provided there's some documentation __at least__ so people can use it on Linux.

**Comment by schwabdidier** [comment]
@kuhlkrein will do that tomorrow. Feel free to add any feedback in order to help him !

**Comment by YannRobert** [comment]
> If you wanted to, you could use this: https://github.com/michel-kraemer/gradle-download-task#download-and-extract-a-zip-file
> Then make an `exec` command to run the `install_all.sh`

That would do the job only for people using gradle (project developers)
but not for end users

**Comment by Tohaker** [comment]
True, we could create a task to run during package app that does a similar thing? We can probably make tasks that create an installer for Linux with them, and MacOS, once that is supported.

**Comment by kuhlkrein** [comment]
Hi, sorry I'm answering a bit late. So yes, for Windows ist is changing nothing compare to the previous version. For linux, the "dependencies" are the need of the drivers installation, as explained in the Readme.md of the TobiieStreamEngineForJava project.

**Comment by kuhlkrein** [comment]
For now the drivers installation script needs some sudo command lines, that's why I keep it like this. If we integrate it to the packageApp I think we need to explicitly discribe to the user what we are asking for right ?

**Comment by kuhlkrein** [comment]
Another idea could be to create a popup window on first linux launch, asking to the user if he/she wants to execute the script maybe ?

**Comment by Tohaker** [comment]
I think we should continue this conversation in an Issue and get this PR merged. Then we can start thinking about how to ship this to Linux users.

**Pull request merged**
